import { createHmac } from "node:crypto";
import type { MaskConfig } from "../config/schema";
import { makeRng, genValue } from "../synthetic/generators";

// What a masked column LOOKS like, computed over a value nobody owns.
//
// The approve sheet's remaining blind spot. A manager ticking "show the real value" for a masked
// field was choosing between two words — `mask` and `unmask` — with no way to see what the masked
// form actually gives a grant holder, so `bucket` with a width of 25,000 and `redact` read as the
// same decision right up until somebody complained the data was useless. Showing the shape is the
// difference between approving a policy and approving a sentence about one.
//
// **Never a stored value.** The sample is generated by the same `genValue` the synthetic seeder
// uses, from a fixed seed, so it is reproducible, obviously fake, and has never been near the
// collection. That is the whole reason this can be rendered to an approver who holds no grant on
// the field: there is nothing here to leak. The alternative — masking one real row and showing it
// — hands the approver a value the mask exists to withhold, transformed or not, and a `first: 3`
// on a real surname is a disclosure.
//
// It mirrors sql/mask.ts expression for expression, because a preview that disagreed with the
// statement would be worse than none. The `never` on the default arm is what makes adding a
// transform to the schema without adding it here a compile error, exactly as it is over there.

/** One field's masked form, and the made-up value it was computed from. */
export type MaskPreview = {
  /** The synthetic input. Fake by construction — see the note above. */
  sample: string;
  /** What a grant holder would receive instead. */
  masked: string;
};

// A fixed key, deliberately not WAREHOUSD_MASK_KEY. The preview needs to show that `hash` yields
// a hex digest of a stable width; using the deployment's real key would put a genuine pseudonym
// of a synthetic value on screen for no gain, and would make the preview fail on a deployment
// that has not set one — which is precisely the deployment where an approver most needs to see
// what they are agreeing to.
const PREVIEW_HASH_KEY = "warehousd-preview";

/** The sample value for a field of this type, from the synthetic generator. */
function sampleFor(field: string, type: string): string {
  // A per-field seed, so the same field previews identically every time it is rendered and two
  // fields do not both come back with the same name.
  let seed = 0;
  for (const ch of `${field}:${type}`) seed = (seed * 31 + ch.charCodeAt(0)) % 2_147_483_647;
  const v = genValue(makeRng(seed + 1), type, field, { min: 40_000, max: 160_000 });
  return typeof v === "object" && v !== null ? JSON.stringify(v) : String(v);
}

/**
 * What `mask` does to a value of `type` on a field of this name.
 *
 * Pure and synchronous: no database, no config beyond the mask itself, nothing to await. That is
 * what lets the approve sheet render it without a round trip and lets a unit test assert the
 * whole table of transforms.
 */
export function maskPreview(field: string, type: string, mask: MaskConfig): MaskPreview {
  const sample = sampleFor(field, type);
  return { sample, masked: maskSample(sample, mask) };
}

/**
 * The transform alone, over a value the caller supplies.
 *
 * Split out from `maskPreview` so the transforms can be asserted against chosen inputs — the
 * length guard on `last4` and the band boundary on `bucket` are edge cases the generator has no
 * reason to produce, and a test that waited for one would be testing the generator.
 *
 * **Only ever a synthetic value.** Nothing may hand this a stored one: masking is computed in the
 * statement (sql/mask.ts) precisely so a raw value never reaches JavaScript, and using this on a
 * real row would reintroduce every exposure that design removes.
 */
export function maskSample(sample: string, mask: MaskConfig): string {
  switch (mask.transform) {
    case "redact":
      return "[redacted]";
    case "last4":
      // The same guard sql/mask.ts states: a value of four characters or fewer would be revealed
      // whole by right(), so it is withheld entirely.
      return sample.length <= 4 ? "••••" : `••••${sample.slice(-4)}`;
    case "first":
      return `${sample.slice(0, mask.chars)}…`;
    case "hash":
      return createHmac("sha256", PREVIEW_HASH_KEY).update(sample).digest("hex");
    case "bucket": {
      // floor(), matching the SQL. A band must not overlap its neighbour.
      const n = Number(sample);
      if (!Number.isFinite(n)) return "";
      return String(Math.floor(n / mask.width) * mask.width);
    }
    case "year":
      return String(new Date(sample).getUTCFullYear());
    case "domain":
      // split_part returns '' for a missing delimiter, and so does this.
      return sample.includes("@") ? (sample.split("@")[1] ?? "") : "";
    default: {
      const never: never = mask;
      throw new Error(`unknown mask transform: ${JSON.stringify(never)}`);
    }
  }
}
