const js = require("@eslint/js");
const tseslint = require("typescript-eslint");

// Until Phase 5.1 this file registered @typescript-eslint and enabled *none* of its rules: the
// whole `rules` block was `{"no-undef": "off"}` plus one no-restricted-imports for the broker. It
// ran in CI and could not have caught anything the audit found.
module.exports = [
  {
    // Patterns must be `**/`-prefixed: a bare `dist/**` only matches the repo
    // root, leaving built artifacts like packages/cli/dist/index.cjs to be
    // linted (and fail) as soon as anyone runs a build before `pnpm lint`.
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      // Generated by `next dev`/`next build` and rewritten on every run.
      "apps/web/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        // An explicit list rather than `projectService`. The type-checked rules need a program, and
        // the programs that cover `test/`, `e2e/` and `scripts/` are the `tsconfig.test.json` /
        // `tsconfig.tools.json` files 5.2 added — projectService only ever looks for a
        // `tsconfig.json`, so under it every one of those files was a parsing error. Same four
        // projects `pnpm typecheck` runs; keep the two lists in step.
        project: [
          "packages/broker/tsconfig.test.json",
          "packages/providers/tsconfig.test.json",
          "packages/cli/tsconfig.test.json",
          "apps/web/tsconfig.test.json",
          "tsconfig.tools.json",
        ],
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // TypeScript already resolves identifiers; `no-undef` only produces false positives here.
      "no-undef": "off",

      // The audit's own findings, expressed as rules:
      //  - no-floating-promises: this codebase is await-heavy and 3.5 was an unawaited-shaped
      //    audit write escaping a verb.
      //  - no-explicit-any: 4.3 removed `any` from src; this keeps it out.
      //  - require-await: an `async` function that never awaits is usually a lost `await`.
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Warn, not error: `!` is the house idiom for `noUncheckedIndexedAccess` on a row that must
      // exist (`rows[0]!`, `c.fields[f]!`). Worth seeing the count; not worth blocking on.
      "@typescript-eslint/no-non-null-assertion": "warn",

      // Off, deliberately, and this is the one place in this config where a recommended rule is
      // switched off rather than tuned — so the reason matters.
      //
      // `@types/pg` types `QueryResult.rows` as `any[]`. Every `r.rows[0].id` in this codebase is
      // therefore an unsafe member access on an `any`, and every value derived from one spreads it.
      // On first run these five rules produced 561 findings, ~72% of the total, essentially all of
      // them that. They were not reporting a defect; they were reporting one library's typing
      // decision, 561 times, loudly enough to bury the 220 findings that *were* defects.
      //
      // What would earn them back: passing a row type at the boundary — `db.query<{ id: string }>(…)`
      // — so `rows` is `{ id: string }[]` and the rules have something true to say. That is a
      // per-call-site change across the whole data layer and belongs to its own piece of work, not
      // to turning the linter on. Until then `strict` + `noUncheckedIndexedAccess` are what hold
      // this line, and they run on every file (see scripts/typecheck.ts).
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  {
    // `onClick={async () => …}` is how React spells an async event handler, and there is no
    // alternative that does not wrap every handler in a synchronous shim. `checksVoidReturn` off for
    // attributes only: the rest of no-misused-promises still applies, including the case that
    // actually bites (a promise handed to something that expects a value, like `Array.filter`).
    files: ["**/*.tsx"],
    rules: {
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
    },
  },
  {
    // The suite deliberately reaches for shapes the app types do not describe — a `pools: any`
    // local, a hand-built row, an `as any` on a Next route handler's argument. Erroring on those
    // would be asking the tests to lie about what they are exercising.
    files: ["**/test/**/*.ts", "**/e2e/**/*.ts", "scripts/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    files: ["packages/broker/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@anthropic-ai/*",
                "next",
                "next/*",
                "@modelcontextprotocol/*",
                "react",
                "react-dom",
              ],
              message:
                "packages/broker must stay free of HTTP/MCP/UI/LLM deps (see docs/architecture.md).",
            },
          ],
        },
      ],
    },
  },
  {
    // Config files and the port guard are plain JS; the type-checked rules have no program for
    // them, and `no-undef` is back on (TypeScript is not resolving these) so Node's globals have
    // to be declared.
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      globals: {
        require: "readonly",
        module: "writable",
        __dirname: "readonly",
        process: "readonly",
        console: "readonly",
      },
    },
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      // eslint.config.js is CommonJS by necessity: the repo is `"type": "module"`-free at the root
      // but flat config is loaded as CJS here, and `require` is how it reads its plugins.
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];
