import { NextRequest } from "next/server";
import {
  auditDestination,
  auditEnabled,
  makeAuditWriter,
  regenerateSynthetic,
} from "@warehousd/broker";
import { getAppPool, getConfig } from "../../../lib/broker";
import { requireRole } from "../../../../lib/authz";

export async function POST(req: NextRequest) {
  const guard = await requireRole(req, "admin");
  if (!guard.ok) return guard.response;

  const { seed } = await req.json().catch(() => ({}));
  if (seed !== undefined && (typeof seed !== "number" || !Number.isFinite(seed)))
    return Response.json({ error: "invalid_seed" }, { status: 400 });

  const app = getAppPool();
  const cfg = getConfig();
  const { collections } = await regenerateSynthetic(app, cfg, guard.workspaceId, seed ?? 42);

  // Destroying and rebuilding a whole environment is a governance event. Audited per
  // collection so the audit browser's collection filter finds it. env is the literal 'dev':
  // this operation cannot touch live, so the caller's env cookie is irrelevant here.
  //
  // Through `makeAuditWriter` like every other decision in the deployment. This used to be a
  // hand-written insert — the last one outside the writer — which meant it went to
  // `app.audit_events` whatever `audit.sink` said, and filled six of the table's columns while
  // leaving `workspace_id`, `via` and `principals` to their defaults. The writer also owns the
  // `audit.enabled` gate, so the flag is honoured in one place rather than remembered here.
  const writer = makeAuditWriter(
    app,
    {
      userId: guard.user.id,
      workspaceId: guard.workspaceId,
      env: "dev",
      allowedCollections: null,
      via: "session",
    },
    auditEnabled(cfg),
    auditDestination(cfg),
  );
  for (const collection of collections) {
    // Not downgraded to a failure: the collections are already truncated and regenerated by the
    // time this runs, so reporting the regen as refused would be the less true of the two answers.
    // A failed write is logged loudly by the writer.
    await writer.allow(collection, { intent: { op: "regen_synth", seed: seed ?? 42 } });
  }

  return Response.json({ ok: true, collections });
}
