import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { mkdtempSync, writeFileSync, readFileSync, rmSync, statSync, existsSync } from "node:fs";
import { loadConfig } from "@warehousd/broker";
import { renderComposeFile } from "../src/deploy/targets/compose";
import { targetFor } from "../src/deploy/targets";
import { ensureState, readState, stateDir } from "../src/state";
import { runDeploy } from "../src/deploy";

// Nothing in this target shells out. The mock is here so that "it ran no command at all" is
// assertable rather than assumed — a Compose deploy that quietly invoked docker would be this
// target's one unacceptable failure.
vi.mock("node:child_process");

// The destroy path reads a typed confirmation from stdin.
let promptAnswer = "";
vi.mock("node:readline/promises", () => ({
  createInterface: () => ({
    question: () => Promise.resolve(promptAnswer),
    close: () => undefined,
  }),
}));

const COMPOSE_FILE = "docker-compose.deploy.yml";
const ENV_FILE = join(".warehousd", "deploy.env");

function projectYaml(database: string): string {
  return `
project: test
deploy:
  target: compose
  app_name: test-app
  region: local
  image: ghcr.io/example/warehousd:1.2.3
  database:
${database}
collections:
  docs:
    description: Docs
    fields:
      title:
        type: text
        posture: allow
`;
}

describe("renderComposeFile", () => {
  it("renders a managed stack with a pgvector service and a named volume", () => {
    expect(
      renderComposeFile({
        appName: "test-app",
        image: "ghcr.io/example/warehousd:1.2.3",
        port: 8722,
        managed: true,
        envPath: ".warehousd/deploy.env",
        contextPath: ".warehousd/deploy/context",
      }),
    ).toMatchInlineSnapshot(`
      "# Generated by \`warehousd deploy\`. Rewritten on every run — keep your edits elsewhere.
      name: test-app

      services:
        server:
          image: ghcr.io/example/warehousd:1.2.3
          restart: unless-stopped
          env_file:
            - .warehousd/deploy.env
          ports:
            - "127.0.0.1:8722:8722"
          volumes:
            - ./.warehousd/deploy/context:/project:ro
          healthcheck:
            test:
              [
                "CMD",
                "node",
                "-e",
                "fetch('http://127.0.0.1:8722/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))",
              ]
            interval: 30s
            timeout: 5s
            start_period: 180s
            retries: 3
          depends_on:
            db:
              condition: service_healthy

        db:
          image: pgvector/pgvector:pg16
          restart: unless-stopped
          environment:
            POSTGRES_USER: warehousd
            POSTGRES_DB: warehousd
            POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?read from .warehousd/deploy.env; pass --env-file}
          volumes:
            - pgdata:/var/lib/postgresql/data
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U warehousd -d warehousd"]
            interval: 5s
            timeout: 5s
            retries: 30

      volumes:
        pgdata:
      "
    `);
  });

  it("renders an attached-database stack with no db service at all", () => {
    expect(
      renderComposeFile({
        appName: "test-app",
        image: "ghcr.io/example/warehousd:1.2.3",
        port: 9000,
        managed: false,
        envPath: ".warehousd/deploy.env",
        contextPath: ".warehousd/deploy/context",
      }),
    ).toMatchInlineSnapshot(`
      "# Generated by \`warehousd deploy\`. Rewritten on every run — keep your edits elsewhere.
      name: test-app

      services:
        server:
          image: ghcr.io/example/warehousd:1.2.3
          restart: unless-stopped
          env_file:
            - .warehousd/deploy.env
          ports:
            - "127.0.0.1:9000:8722"
          volumes:
            - ./.warehousd/deploy/context:/project:ro
          healthcheck:
            test:
              [
                "CMD",
                "node",
                "-e",
                "fetch('http://127.0.0.1:8722/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))",
              ]
            interval: 30s
            timeout: 5s
            start_period: 180s
            retries: 3
      "
    `);
  });
});

describe("the compose target", () => {
  let projectDir: string;

  beforeEach(() => {
    projectDir = mkdtempSync(join(tmpdir(), "wh-compose-"));
    global.fetch = vi.fn(() => Promise.resolve(new Response("OK", { status: 200 })));
  });

  afterEach(() => {
    rmSync(projectDir, { recursive: true, force: true });
    vi.resetAllMocks();
  });

  // The whole point of `appUrl` returning null: there is no stack running yet, so polling one
  // would time out for three minutes and report a failed deploy for a file that rendered fine.
  it("starts nothing, runs no command, and skips the health poll", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    const { execFileSync } = await import("node:child_process");
    await runDeploy(projectDir, { yes: true, allowLocalLogin: true, quiet: true });

    expect(vi.mocked(execFileSync)).not.toHaveBeenCalled();
    expect(vi.mocked(global.fetch)).not.toHaveBeenCalled();
    expect(existsSync(join(projectDir, COMPOSE_FILE))).toBe(true);
  });

  it("writes the env file at mode 0600, with the secrets the other targets send", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    await runDeploy(projectDir, { yes: true, allowLocalLogin: true, quiet: true });

    const path = join(projectDir, ENV_FILE);
    expect(statSync(path).mode & 0o777).toBe(0o600);

    const env = readFileSync(path, "utf8");
    const state = readState(projectDir);
    expect(env).toContain(`WAREHOUSD_DATA_ROLE_PASSWORD=${state?.dataRolePassword}`);
    expect(env).toContain(`BETTER_AUTH_SECRET=${state?.betterAuthSecret}`);
    // The db service interpolates this rather than carrying it, and it has to be the password the
    // app's own APP_DATABASE_URL authenticates with.
    expect(env).toContain(`POSTGRES_PASSWORD=${state?.dbPassword}`);
    expect(env).toContain(`APP_DATABASE_URL=postgres://warehousd:${state?.dbPassword}@db:5432/`);
    // Omitted rather than empty when the target serves no URL of its own: Better Auth falls back
    // to the request, and an empty value would break every callback instead.
    expect(env).not.toContain("BETTER_AUTH_URL");
    // Seeded off app_name, there being no host to seed off.
    expect(env).toContain("WAREHOUSD_ADMIN_EMAIL=admin@test-app.local");

    // The values are generated per deploy, so the file itself cannot be snapshotted; its keys can,
    // and they are the contract — one missing name is a container that boots and then refuses.
    expect(
      env
        .trim()
        .split("\n")
        .map((line) => line.split("=")[0]),
    ).toMatchInlineSnapshot(`
      [
        "APP_DATABASE_URL",
        "WAREHOUSD_DATA_ROLE_PASSWORD",
        "BETTER_AUTH_SECRET",
        "WAREHOUSD_ADMIN_EMAIL",
        "WAREHOUSD_ADMIN_PASSWORD",
        "WAREHOUSD_DEV_CLIENT_SECRET",
        "WAREHOUSD_MASK_KEY",
        "WAREHOUSD_TRUSTED_ORIGINS",
        "POSTGRES_PASSWORD",
      ]
    `);
  });

  // The compose file lands in the project directory, which is usually a git repository;
  // `.warehousd/` is not (.gitignore). So the split has to hold: config in one, secrets in the
  // other. A canary per secret, per Non-negotiable 4's habit.
  it("keeps every secret out of the compose file", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    await runDeploy(projectDir, { yes: true, allowLocalLogin: true, quiet: true });

    const rendered = readFileSync(join(projectDir, COMPOSE_FILE), "utf8");
    const state = readState(projectDir);
    for (const secret of [
      state?.dbPassword,
      state?.dataRolePassword,
      state?.betterAuthSecret,
      state?.adminPassword,
      state?.devClientSecret,
    ]) {
      expect(rendered).not.toContain(secret);
    }
  });

  it("mounts the bundle read-only and publishes the configured port on loopback", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    await runDeploy(projectDir, { yes: true, allowLocalLogin: true, quiet: true });

    const rendered = readFileSync(join(projectDir, COMPOSE_FILE), "utf8");
    expect(rendered).toContain("./.warehousd/deploy/context:/project:ro");
    expect(rendered).toContain(`"127.0.0.1:8722:8722"`);
    expect(rendered).toContain("image: ghcr.io/example/warehousd:1.2.3");
  });

  // There is no host to record, so the outputs carry the address the compose file publishes —
  // the same one `warehousd start` prints for a stack on this machine.
  it("records localhost outputs and a summary that names Compose and not Fly", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    const written: string[] = [];
    const stdout = vi.spyOn(process.stdout, "write").mockImplementation((chunk: unknown) => {
      written.push(String(chunk));
      return true;
    });
    try {
      await runDeploy(projectDir, { yes: true, allowLocalLogin: true });
    } finally {
      stdout.mockRestore();
    }

    const outputs = JSON.parse(
      readFileSync(join(projectDir, ".warehousd", "outputs.deploy.json"), "utf8"),
    );
    expect(outputs.apiUrl).toBe("http://localhost:8722");
    expect(outputs.mcpUrl).toBe("http://localhost:8722/mcp");
    expect(outputs.databaseUrl).toBeNull();

    const summary = written.join("");
    expect(summary).toContain("warehousd deployed to Docker Compose");
    expect(summary).toContain("docker compose --env-file");
    expect(summary).toContain("TLS is yours to terminate");
    expect(summary).not.toMatch(/fly/i);
  });

  // Destroying a stack on the operator's own machine is not this command's to do — it may be under
  // a supervisor, and the volume is the irreversible half.
  it("destroy prints the teardown command and removes nothing", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    await runDeploy(projectDir, { yes: true, allowLocalLogin: true, quiet: true });

    const said: string[] = [];
    const stderr = vi.spyOn(process.stderr, "write").mockImplementation((chunk: unknown) => {
      said.push(String(chunk));
      return true;
    });
    promptAnswer = "test-app";
    try {
      await runDeploy(projectDir, { destroy: true });
    } finally {
      stderr.mockRestore();
    }

    const { execFileSync } = await import("node:child_process");
    expect(vi.mocked(execFileSync)).not.toHaveBeenCalled();
    expect(said.join("")).toContain(`docker compose -f ${COMPOSE_FILE} down`);
    expect(existsSync(join(projectDir, COMPOSE_FILE))).toBe(true);
    expect(existsSync(join(projectDir, ENV_FILE))).toBe(true);
  });

  // The prompt used to promise "this will destroy <app> and its database, which may hold real
  // data" for every target, and then this one printed "Nothing was destroyed". A prompt that
  // overstates what it does is one people learn to type through.
  it("warns about what --destroy actually does here, not about a database", () => {
    const cfg = { deploy: { database: { managed: true } } };
    const warning = targetFor("compose").destroyWarning!({
      projectDir,
      cfg: cfg as never,
      deploy: cfg.deploy as never,
      appName: "test-app",
      region: "local",
      state: null,
      deployDir: join(stateDir(projectDir), "deploy"),
      contextDir: join(stateDir(projectDir), "deploy", "context"),
      localBuild: false,
      say: () => undefined,
    });

    expect(warning).toContain("destroys nothing");
    expect(warning).not.toMatch(/real data/);
    expect(warning).toContain(COMPOSE_FILE);
  });

  // `notes` exists because a Compose deploy renders a file and starts nothing, and the line saying
  // so must not be suppressible. It survived --quiet, which silences `say`, but --json returned
  // before anything read it: a CI caller was told the deploy succeeded and not that nothing ran.
  it("--json carries the target, its database hint and its notes", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    const written: string[] = [];
    const stdout = vi.spyOn(process.stdout, "write").mockImplementation((chunk: unknown) => {
      written.push(String(chunk));
      return true;
    });
    try {
      await runDeploy(projectDir, { yes: true, allowLocalLogin: true, json: true });
    } finally {
      stdout.mockRestore();
    }

    const payload = JSON.parse(written.join(""));
    expect(payload.target).toBe("compose");
    expect(payload.label).toBe("Docker Compose");
    expect(payload.databaseHint).toContain("docker compose");
    expect(payload.notes.join("\n")).toContain("Nothing is running yet");
    expect(payload.notes.join("\n")).toContain("TLS is yours to terminate");
    // Still the whole outputs contract, plus the credentials --json is asked for.
    expect(payload.apiUrl).toBe("http://localhost:8722");
    expect(payload.adminEmail).toBe("admin@test-app.local");
  });

  // The attached-database branch cannot go through runDeploy: pre-flight dials `database.url` for
  // its capability checks, and there is no Postgres here to dial. The branch itself is one line —
  // an attached database has its own password, and POSTGRES_PASSWORD would be interpolated into a
  // db service the compose file does not render.
  it("writes no POSTGRES_PASSWORD when the database is one you already run", async () => {
    writeFileSync(
      join(projectDir, "warehousd.yml"),
      projectYaml("    url: postgres://u:p@db.example.com:5432/warehousd"),
    );
    const cfg = loadConfig(projectDir);
    const deploy = cfg.deploy;
    if (!deploy) throw new Error("the fixture has a deploy block");

    const deployDir = join(stateDir(projectDir), "deploy");
    await targetFor("compose").setSecrets(
      {
        projectDir,
        cfg,
        deploy,
        appName: deploy.app_name,
        region: deploy.region,
        state: ensureState(projectDir),
        deployDir,
        contextDir: join(deployDir, "context"),
        localBuild: false,
        say: () => undefined,
      },
      ["APP_DATABASE_URL=postgres://u:p@db.example.com:5432/warehousd"],
    );

    const env = readFileSync(join(projectDir, ENV_FILE), "utf8");
    expect(env).toContain("APP_DATABASE_URL=postgres://u:p@db.example.com:5432/warehousd");
    expect(env).not.toContain("POSTGRES_PASSWORD");
  });

  // Pre-flight has to stay non-mutating and offline — there is no CLI to probe and no account to
  // authenticate against, so the only thing it can usefully report is what will be written.
  it("pre-flight says what it will write and touches nothing", async () => {
    writeFileSync(join(projectDir, "warehousd.yml"), projectYaml("    managed: true"));

    const checks = await targetFor("compose").preflight({ projectDir, cfg: null, env: {} });

    expect(checks.map((c) => c.id)).toEqual(["compose-renders-only"]);
    expect(checks[0]?.ok).toBe(true);
    expect(checks[0]?.detail).toContain(COMPOSE_FILE);
    expect(existsSync(join(projectDir, COMPOSE_FILE))).toBe(false);
    expect(existsSync(join(projectDir, ENV_FILE))).toBe(false);
  });
});
