import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { loadConfig, type WarehousdConfig } from "@warehousd/broker";
import {
  buildPlan,
  renderPlan,
  planOutro,
  writeMigration,
  existingMigrations,
} from "../src/migrate";
import { resolveTheme } from "../src/ui/theme";
import { writeDeployOutputs } from "../src/state";
import { collectBundlePaths, writeBundle } from "../src/deploy/bundle";
import { renderConfigDiff } from "../src/deploy/diff";
import { preflight } from "../src/deploy/preflight";

const YAML = (amountType: string) => `
project: test
collections:
  orders:
    description: Orders
    fields:
      id:
        type: uuid
        posture: allow
        pk: true
      amount:
        type: ${amountType}
        posture: allow
`;

let projectDir: string;

function config(amountType: string): WarehousdConfig {
  writeFileSync(join(projectDir, "warehousd.yml"), YAML(amountType));
  return loadConfig(projectDir);
}

// The pre-flight and the diff both compare against the last deploy, so a previous one has to exist
// for either to have anything to say.
function recordDeploy(cfg: WarehousdConfig, migrationVersions: string[] = []): void {
  writeDeployOutputs(projectDir, {
    mcpUrl: "https://x.fly.dev/mcp",
    apiUrl: "https://x.fly.dev",
    adminUrl: "https://x.fly.dev/admin",
    databaseUrl: null,
    env: "dev",
    deployedAt: new Date().toISOString(),
    configSnapshot: cfg,
    migrationVersions,
  });
}

beforeEach(() => {
  projectDir = mkdtempSync(join(tmpdir(), "wh-migrate-"));
});
afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
});

// What a terminal gets, with colour off so the strings stay readable in an assertion.
const railTheme = resolveTheme({ isTTY: true, env: { NO_COLOR: "1" } });

describe("buildPlan without a database", () => {
  it("says there is nothing to compare against before the first deploy", async () => {
    config("text");
    const plan = await buildPlan(projectDir);
    expect(plan.source).toBe("none");
    expect(renderPlan(plan)).toMatch(/nothing to compare against/);
    expect(planOutro(plan)).toContain("re-run");
  });

  // The case that matters for a Fly deploy: `database.managed` credentials are generated by
  // `postgres attach` and never reach the CLI, so the snapshot is the only previous state there is.
  it("falls back to the last deployed config snapshot", async () => {
    recordDeploy(config("text"));
    const unchanged = await buildPlan(projectDir, undefined);
    expect(unchanged).toEqual({ source: "config-snapshot", changes: [] });

    config("numeric");
    const changed = await buildPlan(projectDir, undefined);
    expect(changed.source).toBe("config-snapshot");
    expect(changed.changes).toMatchObject([
      { kind: "type_change", field: "amount", from: "text", to: "numeric", destructive: true },
    ]);
  });
});

describe("renderPlan", () => {
  it("separates what needs a migration from what applies on its own", async () => {
    recordDeploy(config("text"));
    // amount retyped (needs a migration) and note added (does not).
    writeFileSync(
      join(projectDir, "warehousd.yml"),
      `${YAML("numeric")}      note:
        type: text
        posture: allow
`,
    );

    const plan = await buildPlan(projectDir);
    const out = renderPlan(plan, railTheme);
    expect(out).toMatch(/1 change\(s\) need a migration/);
    expect(out).toMatch(/needs review\s+orders\.amount/);
    expect(out).toMatch(/1 change\(s\) apply on their own/);
    expect(out).toContain("orders.note");
    // What to do about it is the `└` line now, not a sentence buried in the middle of the list.
    expect(planOutro(plan)).toContain("warehousd migrate generate");
  });

  /**
   * Which glyph each block gets is the whole message.
   *
   * A `▲` on the changes that would destroy data and a `◇` on the ones that will not. It used to
   * be one flat list under two headings, so the difference between "this drops a column" and
   * "this adds an index" was a word.
   */
  it("marks the destructive block as a caution and the additive one as done", async () => {
    recordDeploy(config("text"));
    writeFileSync(
      join(projectDir, "warehousd.yml"),
      `${YAML("numeric")}      note:
        type: text
        posture: allow
`,
    );
    const lines = renderPlan(await buildPlan(projectDir), railTheme).split("\n");
    expect(lines[0]!.startsWith(`${railTheme.s.warn}  `)).toBe(true);
    expect(lines.some((l) => l.startsWith(`${railTheme.s.done}  `))).toBe(true);
  });

  it("says so when nothing changed", async () => {
    const cfg = config("text");
    recordDeploy(cfg);
    const plan = await buildPlan(projectDir);
    expect(renderPlan(plan, railTheme)).toBe(
      `${railTheme.s.done}  No schema changes — config matches the database.`,
    );
    expect(planOutro(plan)).toBe("Edit warehousd.yml, then re-run to see the plan.");
  });

  it("points an additive-only plan at apply rather than at generate", async () => {
    recordDeploy(config("text"));
    writeFileSync(
      join(projectDir, "warehousd.yml"),
      `${YAML("text")}      note:
        type: text
        posture: allow
`,
    );
    expect(planOutro(await buildPlan(projectDir))).toContain("warehousd apply");
  });
});

describe("writeMigration", () => {
  it("writes a numbered file into migrations/ and returns its project-relative path", async () => {
    recordDeploy(config("text"));
    config("numeric");
    const plan = await buildPlan(projectDir);

    const path = writeMigration(projectDir, plan.changes, "widen amount");
    expect(path).toBe(join("migrations", "0001-widen-amount.sql"));

    const sql = readFileSync(join(projectDir, path), "utf8");
    expect(sql).toContain("drop view if exists data_live.v_orders;");
    expect(sql).toContain("-- REVIEW: orders.amount");
    expect(existingMigrations(projectDir)).toEqual(["0001-widen-amount.sql"]);
  });

  it("numbers the next one after the files already there", async () => {
    recordDeploy(config("text"));
    config("numeric");
    const plan = await buildPlan(projectDir);
    writeMigration(projectDir, plan.changes, "first");
    expect(writeMigration(projectDir, plan.changes, "second")).toBe(
      join("migrations", "0002-second.sql"),
    );
  });
});

describe("the deploy image", () => {
  it("bundles migrations/ so the release command can apply them", () => {
    const cfg = config("text");
    expect(collectBundlePaths(cfg, projectDir)).not.toContain("migrations");

    mkdirSync(join(projectDir, "migrations"));
    writeFileSync(join(projectDir, "migrations", "0001-a.sql"), "select 1;");
    expect(collectBundlePaths(cfg, projectDir)).toContain("migrations");

    const out = join(projectDir, "out");
    writeBundle(cfg, projectDir, out);
    expect(existsSync(join(out, "migrations", "0001-a.sql"))).toBe(true);
  });
});

describe("renderConfigDiff", () => {
  // Above the posture changes, which are the existing highest priority: a posture change is a
  // decision the operator meant to make, while this one ends the deploy.
  it("puts a change that needs a migration above everything else", () => {
    const before = config("text");
    const after = loadConfig(
      (() => {
        writeFileSync(
          join(projectDir, "warehousd.yml"),
          `
project: test
collections:
  orders:
    description: Orders
    fields:
      id:
        type: uuid
        posture: allow
        pk: true
      amount:
        type: numeric
        posture: deny
`,
        );
        return projectDir;
      })(),
    );

    const out = renderConfigDiff(before, after);
    expect(out).toMatch(/^REQUIRES MIGRATION/);
    expect(out).toContain("orders.amount");
    expect(out).toContain("warehousd migrate generate");
    // The posture change is still reported, just below it.
    expect(out).toMatch(/HIGH CONSEQUENCE/);
  });

  it("says nothing extra when no change needs a migration", () => {
    const before = config("text");
    expect(renderConfigDiff(before, before)).toBe("no changes");
  });
});

describe("deploy pre-flight", () => {
  const run = () => preflight({ projectDir, env: {}, allowLocalLogin: true });
  const check = (r: Awaited<ReturnType<typeof run>>) =>
    r.checks.find((c) => c.id === "schema-migrations-present");

  it("passes when there is no previous deploy to compare against", async () => {
    config("text");
    expect(check(await run())?.ok).toBe(true);
  });

  it("fails a destructive change with no migration written since the last deploy", async () => {
    recordDeploy(config("text"));
    config("numeric");

    const c = check(await run());
    expect(c?.ok).toBe(false);
    expect(c?.detail).toContain("orders.amount");
    expect(c?.detail).toMatch(/warehousd migrate generate/);
  });

  it("passes once a migration has been added, and defers to the release command", async () => {
    recordDeploy(config("text"));
    config("numeric");
    mkdirSync(join(projectDir, "migrations"));
    writeFileSync(join(projectDir, "migrations", "0001-widen.sql"), "-- reviewed");

    const c = check(await run());
    expect(c?.ok).toBe(true);
    expect(c?.detail).toContain("0001-widen.sql");
    // It must not claim the migration is correct — only the release command can know that.
    expect(c?.detail).toMatch(/release command verifies/);
  });

  // A migration that was already there at the last deploy is not evidence about this change.
  it("does not count a migration that predates the change", async () => {
    mkdirSync(join(projectDir, "migrations"));
    writeFileSync(join(projectDir, "migrations", "0001-old.sql"), "-- from before");
    recordDeploy(config("text"), ["0001-old.sql"]);
    config("numeric");

    expect(check(await run())?.ok).toBe(false);
  });
});
