// The `warehousd migrate` commands: what a destructive config change would do, and the reviewable
// SQL file that lets it through.
//
// Two ways to build the plan, because the database is not always reachable. Against a local stack
// the schema itself is authoritative — it can see drift no config diff explains. Against a Fly
// deployment with `database.managed: true` there is no URL to connect with at all: those
// credentials are generated by `postgres attach` and never leave Fly. There the last deployed
// config snapshot is the only previous state that exists, so that is what gets compared.

import { Pool } from "pg";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  loadConfig,
  planFromSchema,
  planFromConfigs,
  renderMigrationSql,
  nextMigrationFilename,
  projectMigrationStatus,
  type SchemaChange,
  type ProjectMigrationStatus,
} from "@warehousd/broker";
import { readDeployOutputs } from "./state";

export type PlanSource = "schema" | "config-snapshot" | "none";
export type MigratePlan = { source: PlanSource; changes: SchemaChange[] };

export function migrationsDir(projectDir: string): string {
  return join(projectDir, "migrations");
}

export function existingMigrations(projectDir: string): string[] {
  const dir = migrationsDir(projectDir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
}

/**
 * The plan, from whichever source can produce one.
 *
 * `dbUrl` is optional on purpose: `warehousd migrate plan` has to say something useful before a
 * stack is running, and a deploy pre-flight has nothing to connect to.
 */
export async function buildPlan(projectDir: string, dbUrl?: string): Promise<MigratePlan> {
  const cfg = loadConfig(projectDir);

  if (dbUrl) {
    const db = new Pool({ connectionString: dbUrl });
    try {
      return { source: "schema", changes: await planFromSchema(db, cfg) };
    } finally {
      await db.end();
    }
  }

  const prev = readDeployOutputs(projectDir)?.configSnapshot;
  if (!prev) return { source: "none", changes: [] };
  return { source: "config-snapshot", changes: planFromConfigs(prev, cfg) };
}

/** Write the migration and return the path relative to the project. */
export function writeMigration(projectDir: string, changes: SchemaChange[], slug: string): string {
  const dir = migrationsDir(projectDir);
  mkdirSync(dir, { recursive: true });
  const name = nextMigrationFilename(existingMigrations(projectDir), slug);
  writeFileSync(join(dir, name), renderMigrationSql(changes));
  return join("migrations", name);
}

export async function migrationStatus(
  projectDir: string,
  dbUrl: string,
): Promise<ProjectMigrationStatus[]> {
  const db = new Pool({ connectionString: dbUrl });
  try {
    return await projectMigrationStatus(db, projectDir);
  } finally {
    await db.end();
  }
}

// Rendering lives here rather than in program.ts so it can be asserted on directly — every action
// callback in program.ts is argv-driven and only reachable from the e2e suite.
export function renderPlan(plan: MigratePlan): string {
  if (plan.source === "none")
    return "no database and no previous deploy on this machine — nothing to compare against";

  const blocking = plan.changes.filter((c) => c.destructive);
  const additive = plan.changes.filter((c) => !c.destructive);
  if (blocking.length === 0 && additive.length === 0) return "no schema changes";

  const lines: string[] = [];
  if (blocking.length > 0) {
    lines.push(`${blocking.length} change(s) need a migration:`);
    for (const c of blocking)
      lines.push(`  ${c.reviewRequired ? "needs review" : "ready      "}  ${c.detail}`);
    lines.push("");
    lines.push("Run `warehousd migrate generate` to write them as SQL you can review.");
  }
  if (additive.length > 0) {
    if (blocking.length > 0) lines.push("");
    lines.push(`${additive.length} change(s) apply on their own:`);
    for (const c of additive) lines.push(`  ${c.detail}`);
  }
  return lines.join("\n");
}
