import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { resolveBaseImage } from "../fly-toml";
import { stateDir } from "../../state";
import type { PreflightCheck } from "../preflight";
import type { DeployTarget, TargetContext, TargetPreflightInput } from "./types";

/** Written into the project directory, beside warehousd.yml, and safe to commit — see `envPath`. */
const COMPOSE_FILE = "docker-compose.deploy.yml";

/** The same image `warehousd start` runs a managed database on. */
const DB_IMAGE = "pgvector/pgvector:pg16";
const DB_USER = "warehousd";
const DB_NAME = "warehousd";

/** The service name, and therefore the host the server container reaches Postgres on. */
const DB_SERVICE = "db";

/** Where the KEY=VALUE lines every other target sends as secrets are written instead. */
function envPath(projectDir: string): string {
  return join(stateDir(projectDir), "deploy.env");
}

/** Paths inside the compose file are relative to it, so it travels with the directory. */
function relativePaths(ctx: TargetContext): { env: string; context: string } {
  return {
    env: relative(ctx.projectDir, envPath(ctx.projectDir)),
    context: relative(ctx.projectDir, ctx.contextDir),
  };
}

/** The command that starts the stack. Printed rather than run: this target starts nothing. */
function upCommand(env: string): string {
  return `docker compose --env-file ${env} -f ${COMPOSE_FILE} up -d`;
}

/**
 * The compose file, rendered the way `fly.toml` and `railway.json` are — a string template, not a
 * YAML writer. A dependency that serialises three known services would be a dependency in
 * `packages/cli` to avoid indentation bugs in a file this module is the only author of.
 *
 * What is here and why:
 *
 * - **No secret appears in it.** It lands in the project directory, which is usually a git
 *   repository; `.warehousd/` is not (see .gitignore). Everything sensitive lives in the env file,
 *   mode 0600, which the server reads through `env_file` and which `POSTGRES_PASSWORD` is
 *   interpolated from — hence `--env-file` on the printed command, and the `:?` that refuses to
 *   start a database with an empty password rather than one with a guessable one.
 * - **`/project` is read-only.** The bundle is input: nothing in the container writes to it (the
 *   entrypoint only reads `WAREHOUSD_PROJECT_DIR`), and a bind mount is the one place where that
 *   can be enforced rather than assumed.
 * - **Published on loopback**, like `warehousd start`. Outside Fly, TLS is the operator's
 *   responsibility (SECURITY.md), so the default is a port a reverse proxy can reach and the
 *   internet cannot. Widening it is one edit, in a file the operator owns.
 * - **The healthcheck repeats the image's own.** `depends_on: service_healthy` needs one declared
 *   here to gate the server on Postgres being ready, and the bootstrap runs before `next start`
 *   binds — which is what `start_period` covers.
 * - **`db` only under `managed: true`.** With a `url:` the database is somewhere else entirely and
 *   a second Postgres in the stack would be an empty one nothing connects to.
 */
export function renderComposeFile(o: {
  appName: string;
  image: string;
  port: number;
  managed: boolean;
  envPath: string;
  contextPath: string;
}): string {
  const server = `  server:
    image: ${o.image}
    restart: unless-stopped
    env_file:
      - ${o.envPath}
    ports:
      - "127.0.0.1:${o.port}:8722"
    volumes:
      - ./${o.contextPath}:/project:ro
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:8722/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))",
        ]
      interval: 30s
      timeout: 5s
      start_period: 180s
      retries: 3`;

  if (!o.managed) {
    return `# Generated by \`warehousd deploy\`. Rewritten on every run — keep your edits elsewhere.
name: ${o.appName}

services:
${server}
`;
  }

  return `# Generated by \`warehousd deploy\`. Rewritten on every run — keep your edits elsewhere.
name: ${o.appName}

services:
${server}
    depends_on:
      ${DB_SERVICE}:
        condition: service_healthy

  ${DB_SERVICE}:
    image: ${DB_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?read from ${o.envPath}; pass --env-file}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pgdata:
`;
}

// Nothing here shells out or dials anything, so every method is a plain function handing back a
// settled promise rather than an `async` one with nothing to await — the same shape fly.ts uses for
// its synchronous `execFileSync` calls.

/**
 * What this target will write, and what it will not do.
 *
 * There is no CLI to probe and no account to be authenticated against, so the useful thing to say
 * is the one an operator expecting a Fly-shaped deploy would otherwise find out afterwards: the
 * files land here and the stack stays stopped. The region is not checked because Compose has no
 * regions; it stays a required config key with no meaning here.
 */
function preflight(input: TargetPreflightInput): Promise<PreflightCheck[]> {
  return Promise.resolve([
    {
      id: "compose-renders-only",
      ok: true,
      detail:
        `writes ${COMPOSE_FILE} and ${relative(input.projectDir, envPath(input.projectDir))} — ` +
        `nothing is started, and no machine but this one is touched`,
    },
  ]);
}

/** Nothing to create: the stack exists once the operator runs it. */
function ensureApp(): Promise<void> {
  return Promise.resolve();
}

/**
 * The `db` service's URL, on the compose network.
 *
 * A real URL rather than Fly's null: nothing injects one here, and `db` is reachable from the
 * server container by service name. The password is the one already in state.json, which is what
 * `POSTGRES_PASSWORD` in the env file carries into the database container — the two have to be the
 * same value or the app authenticates against a database it just created and cannot enter.
 */
function provisionDatabase(ctx: TargetContext): Promise<string | null> {
  if (!ctx.state) {
    throw new Error("Cannot provision a Compose database without generated state");
  }
  return Promise.resolve(
    `postgres://${DB_USER}:${ctx.state.dbPassword}@${DB_SERVICE}:5432/${DB_NAME}`,
  );
}

/**
 * The env file, mode 0600, which is this target's equivalent of `flyctl secrets import`.
 *
 * `POSTGRES_PASSWORD` is appended under `managed: true` because the compose file interpolates it
 * rather than carrying it: see the note on `renderComposeFile`. It reaches the server container
 * too, through `env_file`, where nothing reads it.
 */
function setSecrets(ctx: TargetContext, lines: string[]): Promise<void> {
  if (!ctx.state) {
    throw new Error("Cannot write Compose secrets without generated state");
  }
  const all = ctx.deploy.database.managed
    ? [...lines, `POSTGRES_PASSWORD=${ctx.state.dbPassword}`]
    : lines;

  mkdirSync(stateDir(ctx.projectDir), { recursive: true });
  writeFileSync(envPath(ctx.projectDir), `${all.join("\n")}\n`, { mode: 0o600 });
  return Promise.resolve();
}

/** Renders the compose file. No image is built, nothing is pushed, and nothing is started. */
function deploy(ctx: TargetContext): Promise<void> {
  const paths = relativePaths(ctx);
  writeFileSync(
    join(ctx.projectDir, COMPOSE_FILE),
    renderComposeFile({
      appName: ctx.appName,
      image: resolveBaseImage(ctx.cfg),
      port: ctx.cfg.server.port,
      managed: ctx.deploy.database.managed === true,
      envPath: paths.env,
      contextPath: paths.context,
    }),
  );
  return Promise.resolve();
}

/**
 * Prints the teardown command rather than running it.
 *
 * Every other target destroys something it created on a machine it owns. Here the stack is running
 * on the operator's, possibly under a supervisor that would restart it, and `docker compose down`
 * from inside a deploy tool would be this command reaching further than it was asked to. The
 * volume is named separately because losing it is the irreversible half.
 */
function destroy(ctx: TargetContext): Promise<void> {
  const paths = relativePaths(ctx);
  ctx.say(
    `Nothing was destroyed — a Compose stack runs on your machine, not on a target this command ` +
      `controls.\n\n  docker compose -f ${COMPOSE_FILE} down\n\n` +
      `Add --volumes to that command to delete the database with it. ${paths.env} and ` +
      `${COMPOSE_FILE} are left in place; delete them by hand.`,
  );
  return Promise.resolve();
}

/**
 * null: nothing is running, so there is nothing to poll and no address to print.
 *
 * `runDeploy` reads that as "skip the health check", omits `BETTER_AUTH_URL` from the secrets, and
 * records `http://localhost:<port>` in the outputs — the address the compose file publishes.
 */
function appUrl(): Promise<string | null> {
  return Promise.resolve(null);
}

/**
 * What is left for the operator to do, and what is theirs to secure.
 *
 * These reach the summary panel rather than `say`, which `--json` and `--quiet` silence: a deploy
 * that renders a file and stops is useless if the line telling you to start it can be suppressed.
 */
function notes(ctx: TargetContext): string[] {
  const paths = relativePaths(ctx);
  return [
    `Nothing is running yet — start it: ${upCommand(paths.env)}`,
    `Ship ${COMPOSE_FILE}, ${paths.env} (mode 0600) and ${paths.context}/ together.`,
    `TLS is yours to terminate: the server is published on 127.0.0.1:${ctx.cfg.server.port} only, ` +
      `for a reverse proxy to sit in front of. Sessions and OAuth codes cross that wire.`,
  ];
}

export const compose: DeployTarget = {
  id: "compose",
  label: "Docker Compose",
  databaseHint: `the \`${DB_SERVICE}\` service — \`docker compose -f ${COMPOSE_FILE} exec ${DB_SERVICE} psql -U ${DB_USER} ${DB_NAME}\``,
  // Compose has no regions, and `region` is a required key with nothing to say here. "local" is
  // the honest placeholder — a machine the operator runs — and nothing validates it.
  exampleRegion: "local",
  preflight,
  ensureApp,
  provisionDatabase,
  setSecrets,
  deploy,
  destroy,
  appUrl,
  notes,
};
